PersonalBlog/Controllers/BlogPostController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PersonalBlog.Models;
using PersonalBlog.Services;

namespace PersonalBlog.Controllers
{ 
    [Authorize()]
    public class BlogPostController : BaseController
    {
        private BlogPostService bps = null;

        public BlogPostController() : base() {
            this.bps = base.GetBlogPostService();
        }

        //
        // GET: /BlogPost/

        public ViewResult Index(string status) {
            ViewBag.Title = "Postings Admin";
            ViewBag.ShowRightBlocks = false;
            status = SessionValue(@"BlogPostController.filter.status", status, BlogPost.StatusPublished);
            ViewBag.status = this.GetPublishStatusList(status);
            ViewBag.Postings = this.bps.List(status);
            return View();
        }

        private IEnumerable<SelectListItem> GetPublishStatusList(string currentStatus = BlogPost.StatusNew)
        {
            return new SelectListItem[]
                {
                    this.CreateListItem(currentStatus, BlogPost.StatusPublished, @"Published"),
                    this.CreateListItem(currentStatus, BlogPost.StatusNew, @"New"),
                    this.CreateListItem(currentStatus, BlogPost.StatusArchived, @"Archived"),
                    this.CreateListItem(currentStatus, BlogPost.StatusSpecialPage, @"Special Pages")
                };
        }

        private SelectListItem CreateListItem(string selectedStatus, string status, string title)
        {
            return new SelectListItem() { Selected = (selectedStatus == status), Text = title, Value = status };
        }

        //
        // GET: /BlogPost/Details/5

        public ViewResult Details(string id)
        {
            ViewBag.ShowRightBlocks = false;
            BlogPost blogpost = this.bps.FindByID(id);
            return View(blogpost);
        }

        //
        // GET: /BlogPost/Create

        public ActionResult Create()
        {
            ViewBag.Title = @"New Blog Post";
            ViewBag.ShowRightBlocks = false;
            var model = new BlogPostViewModel()
                {
                    BlogPost = new BlogPost()
                        {
                            PublishStatus = BlogPost.StatusNew,
                            Author = User.Identity.Name,
                            ContentType = @"H",
                            CreateDate = DateTime.Now
                        },
                    PublishStatuses = this.GetPublishStatusList()
                };
            return View(model);
        } 

        //
        // POST: /BlogPost/Create

        [HttpPost]
        public ActionResult Create(BlogPostViewModel model)
        {
            if (ModelState.IsValid)
            {
                this.bps.Save(model.BlogPost);
                
                return RedirectToAction("Index");  
            }

            model.PublishStatuses = this.GetPublishStatusList();
            return View(model);
        }
        
        //
        // GET: /BlogPost/Edit/5
 
        public ActionResult Edit(string id)
        {
            var model = new BlogPostViewModel()
                {
                    BlogPost = this.bps.FindByID(id),
                    PublishStatuses = this.GetPublishStatusList()
                };
            return View(model);
        }

        //
        // POST: /BlogPost/Edit/5

        [HttpPost]
        public ActionResult Edit(BlogPostViewModel model)
        {
            if (ModelState.IsValid)
            {
                this.bps.Save(model.BlogPost);
                return RedirectToAction("Index");
            }

            model.PublishStatuses = this.GetPublishStatusList();
            return View(model);
        }

        //
        // GET: /BlogPost/Delete/5
 
        public ActionResult Delete(string id)
        {
            BlogPost model = this.bps.FindByID(id);
            return View(model);
        }

        //
        // POST: /BlogPost/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(string id)
        {
            BlogPost model = this.bps.FindByID(id);
            this.bps.Delete(id);
            return RedirectToAction("Index");
        }

        protected string SessionValue(string key, string inputValue, string defaultValue) {
            string ret;
            if (string.IsNullOrEmpty(inputValue)) {
                ret = Session[key] as string;
                if (string.IsNullOrEmpty(ret)) {
                    ret = defaultValue;
                }
            } else {
                ret = inputValue;
            }
            if (ret != defaultValue) {
                Session[key] = ret;
            }
            return ret;
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
        }
    }
}

PersonalBlog/Views/Shared/_BlogPostBlock.cshtml
@using PersonalBlog.Models
@model BlogPost
<div class="post-meta col span-2">
    <span style="border: none; text-align: right; margin-right: .25em;">@Model.CreateDate.ToString("MMM dd")
        <span style="border: none; font-size: 14px; font-weight: normal; color: #707070; padding-top: .25em;">@Model.CreateDate.ToString("h:mm tt")</span>
    </span>
    @if (@Model.Comments.Count > 0) {
        <ul>
            <li>@Model.Comments.Count comments</li>
        </ul>
    }
</div>
<div class="post-content last span-9 nudge-2">
    <h2>@Model.Title
    @if (Request.IsAuthenticated) {
        <a style="position: absolute; right: 24px; padding-top: 4px; font-size: 14px; font-weight: normal;" href="@Url.Action("Edit", "BlogPost", new { id = Model.Id })" title="Edit posting">(edit)</a>
    }
    </h2>
    @Html.Raw(Model.Content)
</div>

PersonalBlog/Views/Shared/_Layout.cshtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
@using PersonalBlog.Controllers
@{
    var siteTitle = @System.Configuration.ConfigurationManager.AppSettings["SiteTitle"];
    if (string.IsNullOrEmpty(siteTitle) == true) { siteTitle = @"Unnamed Site"; }

    if (ViewBag.ShowRightBlocks == null) { ViewBag.ShowRightBlocks = true; }
}
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>@siteTitle - @ViewBag.Title</title>
    <link rel="stylesheet" href="@Url.Content("~/Content/blog.css")" type="text/css" media="screen" title="blog" />
    <script src="@Url.Content("~/Scripts/jquery-1.5.1.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/modernizr-1.7.min.js")" type="text/javascript"></script>
</head>
<body>
    <div id="wrapper" class="span-12">
        <div id="pages">
            <ul>
                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                <li>@Html.ActionLink("About", "About", "Home")</li>
                <li>@Html.ActionLink("Archives", "Archive", "Home")</li>
                @if (Request.IsAuthenticated)
                {
                    <li>@Html.ActionLink("Admin", "Index", "BlogPost")</li>
                    <li>@Html.ActionLink("Post", "Create", "BlogPost")</li>
                }
            </ul>
            <div style="float: right;">@Html.Partial("_LogOnPartial")</div>
        </div>
        <div id="header" class="col last span-12">
            <img style="float: right; clear: left; border: none; height: auto;" src="@Url.Content("~/Content/images/postcard.jpg")"/>
            <h1>@ViewBag.Title</h1>
            <h2>
                <span class="by">@siteTitle</span></h2>
        </div>
        @if (ViewBag.ShowRightBlocks)
        {
            <div id="content" class="col span-9">
                @RenderBody()
            </div>
            <div id="sidebar" class="col last span-3">
                @RenderSection("sidebar", false)
            </div>
        } else
        {
            <div id="content" class="col span-12">
                @RenderBody()
            </div>
        }
        <div id="footer">
            <p id="foo">
                <em>personal</em> blog, version @typeof(BlogPostController).Assembly.GetName().Version</p>
            <p style="color: #222;">
                Copyright © 2011 Michael Tutty. All rights reserved.</p>
            <p>
                Layout based on the <em>Experimental</em> theme by <a href="http://www.rodrigogalindez.com/wordpress-themes/" title="Rodrigo Galindez" style="color: #555; font-weight: normal; text-decoration: underline;">Rodrigo Galindez</a></p>
        </div>
    </div>
</body>
</html>

PersonalBlog/Views/Shared/_LogOnPartial.cshtml
@if(Request.IsAuthenticated) {
    <text><strong>@User.Identity.Name</strong>!
    [ @Html.ActionLink("Log Off", "LogOff", "Account") ]</text>
}
else {
    @:[ @Html.ActionLink("Log On", "LogOn", "Account") ]
}